version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - todo_list_default
    environment:
      - DB_NAME=Todo
      - DB_USER=Blink
      - DB_PASSWORD=#Blink2002
      - DB_HOST=postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Todo
      POSTGRES_USER: Blink
      POSTGRES_PASSWORD: "#Blink2002"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - todo_list_default

volumes:
  postgres_data:

networks:
  todo_list_default:
    external: true
